return {
  -- -- enabled = false,
  -- "stevearc/conform.nvim",
  -- event = { "BufReadPre", "BufNewFile" },
  -- config = function()
  --   local conform = require "conform"
  --
  --   conform.setup {
  --     formatters_by_ft = {
  --       -- javascript = { "biome-check" },
  --       -- typescript = { "biome-check" },
  --       -- javascriptreact = { "biome-check" },
  --       -- typescriptreact = { "biome-check" },
  --       --             css = { "biome-check" },
  --       --             html = { "biome-check" },
  --       -- svelte = { "prettier" },
  --       -- json = { "prettier" },
  --       -- yaml = { "prettier" },
  --       -- graphql = { "prettier" },
  --       -- l16:03iquid = { "prettier" },
  --       -- cs = { "omnisharp" },
  --       cs = { "csharpier" },
  --       lua = { "stylua" },
  --       typst = { "typstyle" },
  --       -- python = { "black" },
  --       markdown = { "prettier", "markdown-toc" },
  --       -- ["markdown.mdx"] = { "prettier", "markdownlint", "markdown-toc" },
  --     },
  --     -- format_on_save = {
  --     -- 	lsp_fallback = true,
  --     -- 	async = false,
  --     -- 	timeout_ms = 1000,
  --     -- },
  --   }
  --   -- Configure individual formatters
  --
  --   vim.api.nvim_create_autocmd("BufWritePre", {
  --     pattern = "*",
  --     callback = function(args)
  --       require("conform").format { bufnr = args.buf }
  --     end,
  --   })
  --   -- vim.keymap.set({ "n", "v" }, "<leader>mp", function()
  --   --   conform.format {
  --   --     lsp_fallback = true,
  --   --     async = false,
  --   --     timeout_ms = 1000,
  --   --   }
  --   -- end, { desc = "Format whole file or range (in visual mode) with" })
  -- end,
}
